services: mongodb
language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - jruby-19mode
  - jruby-20mode
  - rbx-2.1.1
  - rbx-head
  - rbx-19mode

gemfile:
  - Gemfile
  - gemfiles/mongoid-3.0.gemfile
  - gemfiles/mongoid-3.1.gemfile
  - gemfiles/mongoid-4.0.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-head

